### ISSUE TITLE
TypeError: finalQuery.match is not a function

### ISSUE THREAD

**Issue by FredTheNoob** [Solaris9/erela.js-spotify#14]
When searching with my manager I get this error:

![image](https://user-images.githubusercontent.com/43958385/108595674-66f15700-7381-11eb-8855-cf4df3c20ab8.png)

**Comment by FredTheNoob** [comment]
Whoops. It would seem that the search requires a string specifically. I was passing an array, as I was able to without the plugin.

**Comment by Solaris9** [comment]
Playing around I was able to recreate this by passing a [falsy value](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) in the query property etc:

```js
manager.search({ query: "" })
```

This is because the transpiled code is this:
```js
const finalQuery = query.query || query;
``` 

If the query property is false it will use the right hand side which is the object and the object does not have a match function in it. A fix would be checking if the user provides a valid value inside of Erela itself.
