### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by joeyk710** [Solaris9/erela.js-spotify#18]
The Documentation links do not work at all. Please fix them for people who need them.

[https://github.com/MenuDocs/erela.js-spotify#documentation--guides](https://github.com/MenuDocs/erela.js-spotify#documentation--guides)

**Comment by Solaris9** [comment]
The documentation is still currently hosted on my personal VPS, the MenuDocs team is current working on putting their own documentation up, it might not be soon because they are working on Erela related stuff and on other stuff in the background. A current fix would making a PR to change the URL for now with a disclaimer, whether it's published to NPM is another story. But for now you can use <https://solaris.codes/projects/erelajs> and <https://solaris.codes/projects/erelajs/guides/introduction.html>.

**Comment by Strandxo** [comment]
I think the reply from Solaris is a satisfactory response to this so I'll leave it as that :)
